### PR TITLE
Expose tokenization to GraphQL

### PR DESCRIPTION
**Pull request by andrewbranch**

### CODE REVIEW

**Comment by janosh** [comment]
I think this merge introduced a bug. `gatsby develop` is now failing for me with

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

createNodeId is not a function

   7 |     tags
  14 |     ...cover
  15 |   }
  16 |   timeToRead
> 17 |   excerpt(pruneLength: 200)
```
where it used to work fine with the alpha from two days ago.

**Comment by andrewbranch** [comment]
Hmmm... it looks like this might be gatsby-plugin-mdx’s fault. They’re not passing all the same arguments that gatsby-transformer-remark does. I’ll see if I can submit a PR.

**Comment by andrewbranch** [comment]
I get a successful build with this, though looks like I can’t run your site locally without an Algolia development key 😄 

https://github.com/gatsbyjs/gatsby/pull/20879

**Comment by janosh** [comment]
@andrewbranch Damn your quick! Thanks a lot for looking into this and submitting a fix it on the spot! 👍

**Pull request merged**
