### PR TITLE
Fixes axe rule scrollable-region-focusable

### PR DESCRIPTION
**Pull request by alexangas**

### CODE REVIEW

**Comment by alexangas** [comment]
Hello! I recently ran [cypress-axe](https://www.npmjs.com/package/cypress-axe) over my Gatsby blog which uses `gatsby-remark-vscode` for its code formatting. Unfortunately it found that the code blocks are inaccessible via keyboard, something I could also reproduce.

Hence I implemented the fix linked by axe to https://dequeuniversity.com/rules/axe/3.4/scrollable-region-focusable, which simply adds `tabindex=0` to the containing `pre` tag. This resolves the issue.

**Comment by andrewbranch** [comment]
Hi, thanks for taking the time to put this together! Accessibility is super important so I definitely want to make sure this plugin is getting it right.

I’m a little torn on whether this is correct. I understand the purpose, but I can’t find any guidelines in WCAG that support axe’s conclusion. The WCAG success criterion they cite, [2.4.7 Focus Visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html), doesn’t seem relevant to their rule at all. (The criterion only states that there must be a visible indication of which element is focused, and doesn’t say anything about what elements should be focusable.) I reviewed the rest of WCAG 2.1 and didn’t find any mention of whether scroll containers should be focusable.

Without hard guidance from W3C, I went researching prominent sites that display blocks of code that I thought would be likely to get accessibility right.

- First off, [gatsby-remark-prismjs](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/) doesn’t make their code blocks focusable, though I don’t put a ton of stock in that.

- GitHub doesn’t make their code blocks focusable:

   ```
   Not focusable, but scrolls way off to the right /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
   ```

- [StackOverflow](https://stackoverflow.com/questions/61737700/how-can-i-use-thread-sleep-for-every-string-in-my-program) doesn’t make their code blocks focusable.

- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) doesn’t make their code blocks focusable.

- [Google’s developer documentation](https://developers.google.com/maps/documentation/javascript/tutorial) lacks focusable code blocks.

- [W3C’s own examples for how to meet SC 2.4.7](https://www.w3.org/WAI/WCAG21/Techniques/css/C15) have scrollable code blocks that aren’t focusable.

The only prominent example I found where this pattern _is_ implemented is in some of [Microsoft’s 
developer documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp).

It seems to me that axe formed their own opinion here without any relevant documentation to back it up. I don’t necessarily think it’s a bad opinion, but I’m a little hesitant to go against the grain of so many major players who ought to know what they’re doing. (Personally, I think this should be a problem for browser vendors, as this is only a problem for scrollable containers once the content size actually exceeds the scroll size, but that’s neither here nor there.)

I’d like to understand the problem space and existing discussion before forging ahead. Do you have any further information that would be helpful in this investigation? If not, I may try to get in touch with the folks at W3C for clarification.

**Comment by alexangas** [comment]
Hello Andrew,

First of all - thank you for your thorough research on this! With hindsight, I should have made this an issue first nor PR so apologies for that.

From a usability perspective, I think it makes sense to be able to tab through and have focus on code blocks. However as your research has found, this does not appear to be industry standard. As a counterpoint though, a brief search doesn't seem to bring up any discussion on the matter, so maybe it's not thought about? If you know of someone to contact at W3C, it would be interesting to hear their viewpoint.

In terms of this particular PR, if this behaviour was to go in, it should probably not be default and instead be enabled with an option.

**Comment by alexangas** [comment]
Hello again @andrewbranch , I was just wondering if you'd got anywhere further with this. If not, I was thinking of opening an issue on the https://github.com/dequelabs/axe-core repo about it.

I've read further on this and am not clear.

**Comment by andrewbranch** [comment]
I haven’t done anything with this yet. Please let me know what the folks behind axe have to say! Would you mind opening an issue so we can continue future discussion there? I’m going to close this PR for now, but if we reach consensus that it’s definitely correct, we can reopen. If the response from axe lacks backing from a spec, I’ll move forward with opening an issue with W3C. Thanks!

**Pull request closed without merging**
