### PR TITLE
feat: allow manual dark/light mode

### LINKED ISSUE #39: Allow manual switch of dark/light mode
First I would like to say this is a great idea! :)

Now to the matter at hand, `prefers-color-scheme: dark` is all the hot fuss, but I would like to allow my users to override that if they want, so I have a **switch** to select the themes.

Is there an easy way to switch themes like that? Be it a `css` variable or a `className`?

### PR DESCRIPTION
**Pull request by codepunkt**
fixes #39

- [ ] adjust documentation
- [ ] test

### CODE REVIEW

**Comment by codepunkt** [comment]
I'm using this with `gatsby-plugin-use-dark-mode`, which sets a class on the documentElement. Configuration of `gatsby-remark-vscode` looks like this:

```js
{
  resolve: 'gatsby-remark-vscode',
  options: {
    colorTheme: {
      defaultTheme: 'Slack Theme Ochin',
      prefersDarkTheme: 'Ayu Mirage',
    },
    injectStyles: true,
    extensionDataDirectory: path.resolve(
      'vendor/gatsby-remark-vscode-extensions'
    ),
    selectorDark: '.dark-mode',
    extensions: [
      { identifier: 'teabyii.ayu', version: '0.18.0' },
      { identifier: 'felipe-mendes.slack-theme', version: '1.9.10' },
      {
        identifier: 'jpoissonnier.vscode-styled-components',
        version: '0.0.26',
      },
    ],
  },
},
```

**Comment by andrewbranch** [comment]
Thanks for taking the time to open this!

I’ve spent the last couple hours trying to think about this from a high level. I think the strategy of simply _substituting_ the media query for a parent class name might be too implementation-specific to use-dark-mode. I can imagine others having a need to still use the media query but _also_ respond to a class name somehow. I would also love for this to be able to handle more than just a dark/light switch—if we’re responding to parent selectors, I see no reason why someone shouldn’t be able to implement a dropdown theme selector (I think this is a silly feature for a blog, but it would be awesome in a demo site for this plugin itself, and I can also see people wanting to support a light, dark, and high-contrast theme).

Buuut, I’m having trouble coming up with an options API that’s flexible enough for that without being confusing. Also, supporting either of these scenarios would require changing the way the class names and stylesheets get generated, though I think that’s fine.

It’s a fine line we have to walk between overengineering way more flexibility than anyone wants or needs into this vs. painting ourselves into a corner with an API that’s too narrow/specific. I need to think a bit more about this tomorrow. Interested to hear your thoughts too.

**Comment by codepunkt** [comment]
You're welcome - thanks for writing this awesome plugin! 😍 

I love they way you're thoroughly thinking about this - however, i think simple is better and once more use-cases pop up, you can always change later.

I think substituting the media query for a parent class name might be the only good option we have. Most manual implementation will take the media query into account. For my current implementation, that means the internal state that handles dark/light mode will change when the media query matches change/when you change the system settings). If we would render theme styles with both selector prefixes and a media query, implementations that do not take the media query/system settings into account would basically be overruled by the order we render them. If we render the media query after the prefixed styles, someone switching their system styles would see a theme switch - while this could potentially be unwanted by the manual implementation, which actively disregards the media query/system toggle.

In order to implement something like a dropdown theme selector, we could match theme definitions with selectors in the options - e.g.

```js
colorTheme: {
  prefersDarkTheme: { name: 'Ayu Mirage', selector: '.theme-ayu-mirage' },
  prefersLightTheme: [
    { name: 'Material Light', selector: '.theme-material-light' },
    { name: 'Slack Theme Ochin', selector: '.theme-default' }
  ],
  // highContrastBow: { ... },
  // highContrastWoB: { ... },
},
```

But this seems rather complex and there's a lot of ambiguity in the API, which could lead to a lot of frustration. I don't know how -ms-high-contrast stuff interacts with dark and light mode media queries, i'm not sure if matching one of these media queries should always fall back to the default theme for that media query or could stay on a different theme (that is also applicable to the situation) and so on...

**Comment by andrewbranch** [comment]
> simple is better and once more use-cases pop up, you can always change later

I do want to strive for simple, but I also want to avoid future breaking changes and APIs that will become totally obsolete by new ones as much as possible, which is why I’m conflicted on where to strike the balance on this one.

> I think substituting the media query for a parent class name might be the only good option we have.

You might be right on this. I was trying to come up with specific examples of why you might want to respect both the media query and a parent selector, and they all seem like bad ideas in the end. It does seem like if you’re going to have a switch of some kind, it’s best to let that switch be the single source of truth, and let the consumer use `matchMedia` if they want to set the default state of the switch based on system preferences.

> In order to implement something like a dropdown theme selector, we could match theme definitions with selectors in the options

Yeah, I was thinking about an API similar to this. I still want to consider doing something in that vein.

>  I don't know how -ms-high-contrast stuff interacts with dark and light mode media queries

`-ms-high-contrast` is a huge pain, and my optimistic hope is that it will be deprecated in favor of additional `prefers-color-scheme` values. (I actually am unsure of its immediate fate in Chromium-based Edge.) I’m not sure gatsby-remark-vscode can really support -ms-high-contrast; I more meant that someone may provide a manually selectable high-contrast theme, like the [TypeScript playground](https://www.typescriptlang.org/play/) does now. Anyway, the point was just that I do have some desire not to put an artificial limit on selecting between just two themes.

> I'm not sure if every theme always results in the same selectors (such as `mtk1`, `mtk6`, `mtk7` and so on). I'd guess not, so this would be a problem because media query selectors might bleed through the manually set theme where that has holes.

Yeah, I had this same fear. Aaaaand it turns out, this is a bug already. Actually, looking into this, I discovered there’s kind of a significant bug around existing multi-theme support. Tokenizing for two different themes can actually produce different class names. Currently, I loop through each theme that might be applied and generate their CSS. Then, I tokenize and generate HTML _once_. Turns out that the tokenizer is stateful with respect to the theme, so the tokenization is only guaranteed to be correct for the _last_ theme in the array of possible themes.

A possible way to fix this will be to prefix conflicting class names from different themes and put multiple on the same token, e.g.

```diff
- <span class="mkt10">string</span>
+ <span class="default-dark-mkt10 dark-mkt1">string</span>
```

(This is a real example of how “Default Dark+” generates different class names from “Dark” by assigning colors to more scopes.)

So, this will have an impact on the PR here. I think I need to sort this out before accepting a contribution along these lines. After that, I’m getting close to being sold on the idea of only supporting parent-selector- or media-query-based theme selection separately, but I do want to be able to support an array of themes.

**Comment by codepunkt** [comment]
I couldn't follow your tokenizer example, but i'm glad this discussion surfaced a bug. I'm still not sold on multiple theme support because i don't see an apparent usecase (except showing off).

For the time being, i might use my forked branch from this PR for my blog and install it from GitHub. LMK if i can help you with anything, going further.

**Pull request closed without merging**
